### ISSUE TITLE
NullPointerException on SpiceService.addSpiceServiceListener()

### ISSUE THREAD

**Issue by nakardo** [stephanenicolas/robospice#237]
I'm using RoboSpice 1.4.9 along Retrofit. I've several reports of this crash from the Release .apk but I've been unable to reproduce it on debug so far. Here's the Stacktrace. Thanks!

```
java.lang.NullPointerException
at com.octo.android.robospice.SpiceService.addSpiceServiceListener(SpiceService.java:387)
at com.octo.android.robospice.SpiceManager$SpiceServiceConnection.onServiceConnected(SpiceManager.java:1073)
at android.app.ActivityThread$PackageInfo$ServiceDispatcher.doConnected(ActivityThread.java:1247)
at android.app.ActivityThread$PackageInfo$ServiceDispatcher$RunConnection.run(ActivityThread.java:1264)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by romashko** [comment]
Hi, I'm receiving this error with RoboSpice 1.4.14 and Genymotion with Android 2.3.7. No any issue on Android Emulator, but I'm still need to test on Genymotion :( Can you please help?

**Comment by ruscoderalex** [comment]
I don't change anything in the service, but I sometimes override createCacheManager. From what I see in the code the failure to create the cacheManager can lead to null requestProcessor

**Comment by Tooto** [comment]
steps to reproduce this bug:
1. delete application
2. Disable any internet connections
3. install application
4. run app and start CACHED request. 
spiceManager.execute(new PlacesJsonRequest(), JSON_CACHE_KEY, DurationInMillis.ONE_HOUR, new PlacesRequestListener());
5.crash happens

device: sgs4

05-19 16:22:18.966  16427-16427/ru.handh.arenaforum D//SpiceManager.java:212﹕ 16:22:18.973 main SpiceManager started.
05-19 16:22:18.976  16427-16427/ru.handh.arenaforum D//SpiceManager.java:212﹕ 16:22:18.979 main SpiceManager started.
05-19 16:22:18.981  16427-16530/ru.handh.arenaforum V//SpiceManager.java:1191﹕ 16:22:18.985 SpiceManagerThread 0 Binding to service.
05-19 16:22:18.981  16427-16531/ru.handh.arenaforum V//SpiceManager.java:1191﹕ 16:22:18.986 SpiceManagerThread 0 Binding to service.
05-19 16:22:18.981  16427-16531/ru.handh.arenaforum V//SpiceManager.java:1197﹕ 16:22:18.987 SpiceManagerThread 0 Binding to service succeeded.
05-19 16:22:18.981  16427-16531/ru.handh.arenaforum D//SpiceManager.java:1245﹕ 16:22:18.988 SpiceManagerThread 0 Waiting for service to be bound.
05-19 16:22:18.981  16427-16530/ru.handh.arenaforum V//SpiceManager.java:1197﹕ 16:22:18.989 SpiceManagerThread 0 Binding to service succeeded.
05-19 16:22:18.986  16427-16530/ru.handh.arenaforum D//SpiceManager.java:1245﹕ 16:22:18.989 SpiceManagerThread 0 Waiting for service to be bound.
05-19 16:22:19.051  16427-16427/ru.handh.arenaforum W/ContextImpl﹕ Unable to create files subdir /data/data/ru.handh.arenaforum/cache
05-19 16:22:19.061  16427-16427/ru.handh.arenaforum E//SpiceService.java:110﹕ 16:22:19.065 main com.octo.android.robospice.persistence.exception.CacheCreationException: The cache folder /robospice-cache could not be created.
            at com.octo.android.robospice.persistence.file.InFileObjectPersisterFactory.setCacheFolder(InFileObjectPersisterFactory.java:73)
            at com.octo.android.robospice.persistence.file.InFileObjectPersisterFactory.<init>(InFileObjectPersisterFactory.java:48)
            at com.octo.android.robospice.persistence.file.InFileObjectPersisterFactory.<init>(InFileObjectPersisterFactory.java:35)
            at com.octo.android.robospice.persistence.springandroid.json.jackson.JacksonObjectPersisterFactory.<init>(JacksonObjectPersisterFactory.java:18)
            at com.octo.android.robospice.JacksonSpringAndroidSpiceService.createCacheManager(JacksonSpringAndroidSpiceService.java:24)
            at com.octo.android.robospice.SpiceService.onCreate(SpiceService.java:108)
            at com.octo.android.robospice.SpringAndroidSpiceService.onCreate(SpringAndroidSpiceService.java:25)
            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3150)
            at android.app.ActivityThread.access$1900(ActivityThread.java:177)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1531)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5944)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)
05-19 16:22:19.136  16427-16529/ru.handh.arenaforum I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false
05-19 16:22:19.136  16427-16529/ru.handh.arenaforum I/System.out﹕ (HTTPLog)-Static: isShipBuild true
05-19 16:22:19.136  16427-16529/ru.handh.arenaforum I/System.out﹕ (HTTPLog)-Thread-26765-360025949: SmartBonding Enabling is false, SHIP_BUILD is true, log to file is false, DBG is false
05-19 16:22:19.136  16427-16529/ru.handh.arenaforum I/System.out﹕ (HTTPLog)-Static: isSBSettingEnabled false

,...

05-19 16:22:19.216  16427-16427/ru.handh.arenaforum E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: ru.handh.arenaforum, PID: 16427
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.octo.android.robospice.request.RequestProcessor.addSpiceServiceListener(com.octo.android.robospice.request.listener.SpiceServiceListener)' on a null object reference
            at com.octo.android.robospice.SpiceService.addSpiceServiceListener(SpiceService.java:487)
            at com.octo.android.robospice.SpiceManager$SpiceServiceConnection.onServiceConnected(SpiceManager.java:1087)
            at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1265)
            at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1282)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:145)
            at android.app.ActivityThread.main(ActivityThread.java:5944)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1389)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1184)

**Comment by Loda** [comment]
I noticed this bug in production too: 

RoboSprice version 1.4.14

Observed on the following Android OS version : 6.0, 2.3.3, 6.0.1, 4.4.3, 2.3.4, 4.4.5, 5.1.1, 4.0.3, 5.1, 4.4, 5.0.2, 5.0, 4.0.4, 5.0.1, 2.3.6, 4.2.1, 4.1.1, 4.3, 4.4.4, 4.2.2, 4.1.2, 4.4.2, 2.3.5

Mostly occur on device SM-T805 (96%) and/or os version 4.4.2 (58%)

```
0 java.lang.NullPointerException
1 at com.octo.android.robospice.SpiceService.com.octo.android.robospice.persistence.CacheManager createCacheManager(android.app.Application)(SourceFile:487)
2 void addSpiceServiceListener(com.octo.android.robospice.request.listener.SpiceServiceListener)
3 at com.octo.android.robospice.SpiceManager$SpiceServiceConnection.void onServiceConnected(android.content.ComponentName,android.os.IBinder)(SourceFile:1087)
4 at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1064)
5 at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1081)
6 at android.os.Handler.handleCallback(Handler.java:587)
7 at android.os.Handler.dispatchMessage(Handler.java:92)
8 at android.os.Looper.loop(Looper.java:130)
9 at android.app.ActivityThread.main(ActivityThread.java:3687)
10 at java.lang.reflect.Method.invokeNative(Native Method)
11 at java.lang.reflect.Method.invoke(Method.java:507)
12 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
13 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
14 at dalvik.system.NativeStart.main(Native Method)
```

This is one of my top 10 bug report, and the stack does not include any of my code....

**Comment by softwaremaverick** [comment]
Hello,

Just look at that new stuff, I was surprised so much, you have to take a look here <http://phirdewatu.seafrog.org/lnywzl?xtkd>

Typos courtesy of my iPhone, Andrew Clark

**Comment by cbriseno** [comment]
Hello, my project is having this issue as well but, in previous versions it did not happen. Maybe it has to do with new build tools, gradle plugins or support libraries versions?

**Comment by mykolaj** [comment]
It seems that we're talking about two different cases here which may or may not be related:
1. First one is when a RequestProcessor is null.
2. Second is when RS fails to create a cache folder.
First things first. Lets take a look at the only [line](https://github.com/stephanenicolas/robospice/blob/release/robospice-core-parent/robospice/src/main/java/com/octo/android/robospice/SpiceService.java#L128) in a SpiceService code where RequestProcessor is assigned. As we can see, unless we don't mess something up with a createRequestProcessor() function in our own implementation of the SpiceService there's no way for the RequestProcessor to be null. So please make sure that in every custom subclass of the SpiceService, in case onCreate() function is overridden, super.onCreate() call goes first (!). Not last, not second, but first. Or make absolutely sure that before the SpiceService's super.onCreate() function call there's no way that any request is executed or any listener is created and added. In case anyone have a createRequestProcessor() function overridden also make sure that the function has no way to return null.
I'll try to investigate the second case which is about a cache folder in the next few days.

**Comment by adignatov** [comment]
@mykolaj I check onCreate, problem not in it. May be this line
 `cacheManager = createCacheManager(getApplication());` 
in SpiceService.onCreate throw error and createRequestProcessor not calling?
