### ISSUE TITLE
NullPointerException in SpiceRequest.cancel in v1.4.12

### ISSUE THREAD

**Issue by asfdfdfd** [stephanenicolas/robospice#306]
Hey, i've got crash report via Crashlytics.

```
java.lang.NullPointerException
       at com.octo.android.robospice.request.SpiceRequest.cancel(SpiceRequest.java:101)
       at com.octo.android.robospice.request.CachedSpiceRequest.cancel(CachedSpiceRequest.java:83)
       at ru.rocketbank.r2d2.RocketSpiceManager.cancelAllRequestsInternal(RocketSpiceManager.java:812)
       at ru.rocketbank.r2d2.RocketSpiceManager.access$200(RocketSpiceManager.java:31)
       at ru.rocketbank.r2d2.RocketSpiceManager$8.run(RocketSpiceManager.java:786)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
```

RocketSpiceManager is descendant of SpiceManager with some changes to help me cancel requests on event from EventBus. You can look it here https://gist.github.com/asfdfdfd/271c495c0e2b3f86d418/01f58b2fbf03870faf19280cedf8c627935ca7b1. It is mostly copy of SpiceManager, except couple of new functions (at top and the bottom).

Maybe this is error in my code somewhere, but this is pretty strange that code perform null check on "requestCancellationListener" in SpiceRequest and then "requestCancellationListener" is null.

This is not regular exception. My application lives two months in production and i have this exception once.

**Comment by kirisetsz** [comment]
The crash can rarely be found on 1.4.13 release with a probability of 0.005%.

```
java.lang.NullPointerException
	at com.octo.android.robospice.request.SpiceRequest.cancel(SourceFile:103)
	at com.tietie.foundation.util.Views.setImageViewBitmapFromNetwork(SourceFile:71)
        ......
```
