### ISSUE TITLE
java.lang.InterruptedException on Android L Preview using 1.4.13 snapshots

### ISSUE THREAD

**Issue by ffgiraldez** [stephanenicolas/robospice#334]
07-08 23:23:43.736  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/thread.cc:1062] Throwing new exception Attempt to invoke direct method 'void com.octo.android.robospice.SpiceManager.sendRequestToService(com.octo.android.robospice.request.CachedSpiceRequest)' on a null object reference with unexpected pending exception: java.lang.InterruptedException:
07-08 23:23:43.736  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/thread.cc:1062]   at void java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(int) (AbstractQueuedSynchronizer.java:1992)
07-08 23:23:43.736  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/thread.cc:1062]   at void java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() (AbstractQueuedSynchronizer.java:2026)
07-08 23:23:43.736  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/thread.cc:1062]   at java.lang.Object java.util.concurrent.PriorityBlockingQueue.take() (PriorityBlockingQueue.java:510)
07-08 23:23:43.736  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/thread.cc:1062]   at void com.octo.android.robospice.SpiceManager.run() (SpiceManager.java:263)
07-08 23:23:43.736  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/thread.cc:1062]   at void java.lang.Thread.run() (Thread.java:820)
07-08 23:23:43.736  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/thread.cc:1062]
07-08 23:23:44.161  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/thread_list.cc:179] Holding abort lock while sleeping for thread suspension
07-08 23:23:44.161  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/runtime.cc:272] Runtime aborting --- recursively, so no thread-specific detail!
07-08 23:23:44.161  24363-24437/com.jsa.tierradetoros A/art﹕ art/runtime/runtime.cc:272]
07-08 23:23:44.161  24363-24437/com.jsa.tierradetoros A/libc﹕ Fatal signal 6 (SIGABRT), code -6 in tid 24437 (SpiceManagerThr)

**Comment by spark85** [comment]
I have it as well, again with the debugger attached
 Process: com.instaradio, PID: 15091
    java.lang.InterruptedException
            at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:1991)
            at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2025)
            at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:410)
            at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:820)
01-15 13:50:18.232    183-15434/? E/ACDB-LOADER﹕ Error: ACDB AudProc vol returned = -19

**Comment by spark85** [comment]
Sorry, I missed an important line of the trace.  It starts with: 
01-15 13:50:15.856  15091-15272/? E/AndroidRuntime﹕ FATAL EXCEPTION: Loader:HLS

**Comment by engineers-bojan** [comment]
Same error here with debugger attached.

**Comment by viktor1190** [comment]
The same bug, only happens with the debugger attached, when I launch an other activity of my app, then it stop and show ANR message. I think is related with the spice service; when it stop and restart the service and the debugger is attached.
Running on Android 5.0.2, Moto G Second generation OEM
This is my log trace:

V/SpiceAdapter: calling to spiceManager.shouldStop()
D//SpiceManager.java:326: 10:27:36.087 main SpiceManager stopping. Joining
V//SpiceManager.java:767: 10:27:36.097 main Cleared listeners of all requests to launch
V//SpiceManager.java:796: 10:27:36.107 main Cleared listeners of all pending requests
Throwing new exception 'Attempt to invoke direct method 'void com.octo.android.robospice.SpiceManager.sendRequestToService(com.octo.android.robospice.request.CachedSpiceRequest)' on a null object reference' with unexpected pending exception: java.lang.InterruptedException:
  at void java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(int) (AbstractQueuedSynchronizer.java:1991)
  at void java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() (AbstractQueuedSynchronizer.java:2025)
  at java.lang.Object java.util.concurrent.PriorityBlockingQueue.take() (PriorityBlockingQueue.java:510)
  at void com.octo.android.robospice.SpiceManager.run() (SpiceManager.java:263)
  at void java.lang.Thread.run() (Thread.java:820)
Runtime aborting...
Aborting thread:
"SpiceManagerThread 5" prio=5 tid=20 Runnable
  | group="" sCount=0 dsCount=0 obj=0x130ec100 self=0xb8711538
  | sysTid=514 nice=0 cgrp=apps sched=0/0 handle=0xb8b797a0
  | state=R schedstat=( 0 0 0 ) utm=0 stm=0 core=0 HZ=100
  | stack=0xa3f6e000-0xa3f70000 stackSize=1036KB
  | held mutexes= "abort lock" "mutator lock"(shared held)
  native: #00 pc 00004d50  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext_)+23)
  native: #01 pc 000034c1  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext_)+8)
  native: #02 pc 0025bf55  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const_, art::mirror::ArtMethod_)+84)
  native: #03 pc 0023fbd3  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+162)
  native: #04 pc 0022ef41  /system/lib/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread_)+32)
  native: #05 pc 0022f1ab  /system/lib/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+354)
  native: #06 pc 0022f3a3  /system/lib/libart.so (art::Runtime::Abort()+82)
  native: #07 pc 000a7111  /system/lib/libart.so (art::LogMessage::~LogMessage()+1360)
  native: #08 pc 0023db4b  /system/lib/libart.so (art::Thread::AssertNoPendingExceptionForNewException(char const_) const+418)
  native: #09 pc 0024188d  /system/lib/libart.so (art::Thread::ThrowNewException(art::ThrowLocation const&, char const_, char const_)+24)
  native: #10 pc 00068e5b  /system/lib/libart.so (art::ThrowException(art::ThrowLocation const_, char const_, art::mirror::Class_, char const_, std::__va_list_)+306)
  native: #11 pc 000692e7  /system/lib/libart.so (art::ThrowNullPointerExceptionForMethodAccessImpl(art::ThrowLocation const&, unsigned int, art::DexFile const&, art::InvokeType)+254)
  native: #12 pc 00090b63  /system/lib/libart.so (art::JValue art::interpreter::ExecuteGotoImpl<false, false>(art::Thread_, art::MethodHelper&, art::DexFile::CodeItem const_, art::ShadowFrame&, art::JValue)+39962)
  native: #13 pc 0016573b  /system/lib/libart.so (art::interpreter::EnterInterpreterFromDeoptimize(art::Thread_, art::ShadowFrame_, art::JValue_)+258)
  native: #14 pc 001ee5c5  /system/lib/libart.so (art::mirror::ArtMethod::Invoke(art::Thread_, unsigned int_, unsigned int, art::JValue_, char const_)+272)
  native: #15 pc 0022c05d  /system/lib/libart.so (art::InvokeVirtualOrInterfaceWithJValues(art::ScopedObjectAccessAlreadyRunnable const&, art::mirror::Object_, _jmethodID_, jvalue_)+264)
  native: #16 pc 0024278f  /system/lib/libart.so (art::Thread::CreateCallback(void_)+534)
  native: #17 pc 00015e7b  /system/lib/libc.so (__pthread_start(void*)+30)
  native: #18 pc 00013e37  /system/lib/libc.so (__start_thread+6)
  at com.octo.android.robospice.SpiceManager.run(SpiceManager.java:263)
  at java.lang.Thread.run(Thread.java:820)
Pending exception java.lang.InterruptedException thrown by 'java.lang.Object java.util.concurrent.PriorityBlockingQueue.take():512'
java.lang.InterruptedException:
  at void java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(int) (AbstractQueuedSynchronizer.java:1991)
  at void java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await() (AbstractQueuedSynchronizer.java:2025)
  at java.lang.Object java.util.concurrent.PriorityBlockingQueue.take() (PriorityBlockingQueue.java:510)
  at void com.octo.android.robospice.SpiceManager.run() (SpiceManager.java:263)
  at void java.lang.Thread.run() (Thread.java:820)
Dumping all threads without appropriate locks held: thread list lock
All threads:
DALVIK THREADS (37):
"main" prio=5 tid=1 TimedWaiting
  | group="" sCount=0 dsCount=0 obj=0x739d3480 self=0xb83e9568
  | sysTid=32163 nice=0 cgrp=apps sched=0/0 handle=0xb6f63ec8
  | state=S schedstat=( 0 0 0 ) utm=554 stm=59 core=1 HZ=100
  | stack=0xbe674000-0xbe676000 stackSize=8MB
  | held mutexes=
  kernel: futex_wait_queue_me+0xe0/0x108
  kernel: futex_wait+0x170/0x238
  kernel: do_futex+0xfc/0x9fc
...
