### ISSUE TITLE
VerifyError on Android 5.0: Rejecting class GsonObjectPersister that attempts to sub-class erroneous class SpringAndroidObjectPersister

### ISSUE THREAD

**Issue by ajans** [stephanenicolas/robospice#387]
This error pops into Logcat with Robospice 1.4.14 (commit 5f66030) on Android 5.0 (Nexus 10 and Nexus 7) using SpiceArrayAdapter from com.octo.android.robospice.spicelist.simple and the GsonSpringAndroidSpiceService.

The stacktrace and exact error message is as follows:

```
E/art(2849): Rejecting class com.octo.android.robospice.persistence.springandroid.json.gson.GsonObjectPersister that attempts to sub-class erroneous class com.octo.android.robospice.persistence.springandroid.SpringAndroidObjectPersister in /data/app/de.billiger.android-1/base.apk
D//DefaultRequestRunner.java:219(2849): 14:16:08.282 Thread-1181 An unexpected error occurred when processsing request CachedSpiceRequest [requestCacheKey=https://api.billiger.de/content/2.0/get_category_tree, cacheDuration=86400000, spiceRequest=de.billiger.android.categories.CategoryTreeRequest@31262d71]
D//DefaultRequestRunner.java:219(2849): java.lang.VerifyError: Rejecting class com.octo.android.robospice.persistence.springandroid.json.gson.GsonObjectPersister that attempts to sub-class erroneous class com.octo.android.robospice.persistence.springandroid.SpringAndroidObjectPersister (declaration of 'com.octo.android.robospice.persistence.springandroid.json.gson.GsonObjectPersister' appears in /data/app/de.billiger.android-1/base.apk)
D//DefaultRequestRunner.java:219(2849):     at com.octo.android.robospice.persistence.springandroid.json.gson.GsonObjectPersisterFactory.createInFileObjectPersister(GsonObjectPersisterFactory.java:42)
D//DefaultRequestRunner.java:219(2849):     at com.octo.android.robospice.persistence.file.InFileObjectPersisterFactory.createObjectPersister(InFileObjectPersisterFactory.java:115)
D//DefaultRequestRunner.java:219(2849):     at com.octo.android.robospice.persistence.file.InFileObjectPersisterFactory.createObjectPersister(InFileObjectPersisterFactory.java:21)
D//DefaultRequestRunner.java:219(2849):     at com.octo.android.robospice.persistence.CacheManager.getObjectPersister(CacheManager.java:183)
D//DefaultRequestRunner.java:219(2849):     at com.octo.android.robospice.persistence.CacheManager.loadDataFromCache(CacheManager.java:68)
D//DefaultRequestRunner.java:219(2849):     at com.octo.android.robospice.request.DefaultRequestRunner.loadDataFromCache(DefaultRequestRunner.java:262)
D//DefaultRequestRunner.java:219(2849):     at com.octo.android.robospice.request.DefaultRequestRunner.processRequest(DefaultRequestRunner.java:99)
D//DefaultRequestRunner.java:219(2849):     at com.octo.android.robospice.request.DefaultRequestRunner$1.run(DefaultRequestRunner.java:217)
D//DefaultRequestRunner.java:219(2849):     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
D//DefaultRequestRunner.java:219(2849):     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
D//DefaultRequestRunner.java:219(2849):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
D//DefaultRequestRunner.java:219(2849):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
D//DefaultRequestRunner.java:219(2849):     at java.lang.Thread.run(Thread.java:818)
D//DefaultRequestRunner.java:219(2849): Caused by: java.lang.VerifyError: Rejecting class com.octo.android.robospice.persistence.springandroid.SpringAndroidObjectPersister because it failed compile-time verification (declaration of 'com.octo.android.robospice.persistence.springandroid.SpringAndroidObjectPersister' appears in /data/app/de.billiger.android-1/base.apk)
D//DefaultRequestRunner.java:219(2849):     ... 13 more
```

Do you need any more information?

**Comment by stephanenicolas** [comment]
Thx Arne for the PR, we will look into it shortly now. Sorry for the delay, I had real xmas holidays, even a bit extended due to an injury at the right hand. But we are back ;)

**Comment by deinlandel** [comment]
Any updates on this one?
